@startuml

hide circle
skinparam classAttributeIconSize 0

abstract class DataFile

DataFile <|-- DataFileDestroyer
DataFileDestroyer --> "1" Printer : uses >
DataFileDestroyer --> "1" CheatSheetList : references >

hide attributes
hide method

@enduml